### ISSUE TITLE
页面中有embed标签时后台报错！

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Selection-Translator/crx-selection-translate#368]
比如把下面的代码存为html：
``` html
<embed src="https://public.zheng0716.com/static/image/github.svg"/>
```
然后打开chrome，控制台就会报错：
``` log
commons2.js:6 Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at ce (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:6:14092)
    at pe (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:6:14996)
    at Ci (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:6:26749)
    at wi (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:6:26639)
    at VueComponent.Ei.t._compile (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:6:31608)
    at VueComponent.Pi.t.$mount (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:7:6124)
    at VueComponent.It.t._init (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:6:10622)
    at new VueComponent (eval at e (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons2.js:7:7664), <anonymous>:2:47)
    at Object.191 (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/content.js:1:2433)
    at n (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/bundle/commons3.js:1:107)
ce @ commons2.js:6
pe @ commons2.js:6
Ci @ commons2.js:6
wi @ commons2.js:6
Ei.t._compile @ commons2.js:6
Pi.t.$mount @ commons2.js:7
It.t._init @ commons2.js:6
VueComponent @ VM570:2
191 @ content.js:1
n @ commons3.js:1
0 @ content.js:1
n @ commons3.js:1
window.webpackJsonp @ commons3.js:1
(anonymous) @ content.js:1
start.js:14 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at start.js:14
(anonymous) @ start.js:14

```

**Comment by lmk123** [comment]
看起来跟 vuejs/vue#5852 是同一个问题，升级到 v2.x 的 Vue 就可以了，但是划词翻译使用的是 v1.x，升级起来还是比较麻烦的，我近期打算重构一遍划词翻译，完成之后应该就不会有这个问题了。

至于何时重构完成，我也说不准 😂

**Comment by zhengxiaoyao0716** [comment]
ok

**Comment by lmk123** [comment]
新版本会用最新版的 Vue，届时就没有这个问题了，所以这个 issue 我先关闭
