### ISSUE TITLE
我想自己增加一个翻译后把单词推到我自己服务器的功能，但是本地遇到点问题

### ISSUE THREAD

**Issue by jiyarong** [Selection-Translator/crx-selection-translate#582]
我的系统是Macos 10.14.2
Chrome版本是73
我代码拉下来，然后
```
$ npm i
```
再
```
$ npm run build
```
最后拖到chrome里面提示有错误

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

**Comment by jiyarong** [comment]
```
$ npm run dev 
```
也出现了大量的错误

```
ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
 @ ./src/public/bootstrap-lite.scss 4:14-147

ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
 @ ./src/options/options.scss 4:14-140

ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
 @ ./src/popup/popup.scss 4:14-138

ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
 @ ./src/public/widget/style.scss 4:14-144

ERROR in ./src/public/bootstrap-lite.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:398:8)
    at /Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModuleFactory.js:58:13

ERROR in ./src/options/options.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:398:8)
    at /Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModuleFactory.js:58:13

ERROR in ./src/popup/popup.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:398:8)
    at /Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModuleFactory.js:58:13

ERROR in ./src/public/widget/style.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/Compilation.js:398:8)
    at /Users/jiyarong/webs7/crx-selection-translate/node_modules/webpack/lib/NormalModuleFactory.js:58:13
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ENOENT: no such file or directory, scandir '/Users/jiyarong/webs7/crx-selection-translate/node_modules/node-sass/vendor'
Child extract-text-webpack-plugin:
```

**Comment by lmk123** [comment]
看错误提示是你的 node-sass 没有安装成功，按照 lmk123/blog#28 的方法安装一次
